# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"
ignore_deps = ["github.com/coredns/coredns"]

# previous release
previous = "v1.11.1"

pre_release = false

preface = """
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
runc: 1.3.2
Kubernetes: 1.34.1
Linux: 6.12.52
linux-firmware: 20251011
CoreDNS: 1.12.4
etcd: 3.6.5
Flannel: 0.27.4

Talos is built with Go 1.24.9.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"
